
package Frames;

import Classes.Account;
import Classes.Admin;
import Classes.Bank;
import Classes.Client;
import Classes.Employee;
import Classes.Qualification;
import Classes.Transaction;
import Components.MyDialog;
import Components.MyColor;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;




public class Login extends javax.swing.JFrame {

    public static ClientPage cp ;
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        myHeading11 = new Components.MyHeading1();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new Components.PasswordField();
        myButton1 = new myappgui2.MyButton();
        jLabel5 = new javax.swing.JLabel();
        myButton2 = new myappgui2.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        setMinimumSize(new java.awt.Dimension(825, 540));
        setSize(new java.awt.Dimension(400, 300));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(MyColor.white);
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 630));

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\Programming\\java\\Bank management system\\Bank-Managment-System\\Bank System Project\\imgs\\bank.png")); // NOI18N
        jLabel1.setText("jLabel1");

        myHeading11.setText("Welcome Back !");

        jPanel2.setBackground(MyColor.whiteBlue);
        jPanel2.setBorder(new javax.swing.border.LineBorder(MyColor.gray, 1, true));

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\Programming\\java\\Bank management system\\Bank-Managment-System\\Bank System Project\\imgs\\logo.png")); // NOI18N

        jLabel3.setBackground(MyColor.transparent);
        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 0, 22)); // NOI18N
        jLabel3.setText(" Email");

        jTextField1.setBackground(MyColor.transparent);
        jTextField1.setFont(new java.awt.Font("Segoe UI Variable", 0, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setToolTipText("");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(MyColor.grayBold));
        jTextField1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(MyColor.transparent);
        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 0, 22)); // NOI18N
        jLabel4.setText(" Password");

        jTextField2.setBackground(MyColor.transparent);
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(MyColor.grayBold));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));

        myButton1.setForeground(MyColor.white);
        myButton1.setText("Sign In");
        myButton1.setRadius(30);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel5.setForeground(MyColor.black);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("---------------------OR---------------------");

        myButton2.setForeground(MyColor.white);
        myButton2.setText("Sign Up");
        myButton2.setRadius(30);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(173, 173, 173))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(myButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(myHeading11, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(myHeading11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        String email = jTextField1.getText();
        String passwword = jTextField2.getText();
        Client c = new Client();
        Employee e = new Employee();
        Admin a = new Admin();
        
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(MyColor.gray));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(MyColor.gray));
        
        //for test
//            email = "F.Adel@gmail.com";
//            passwword = "F.Adel@";
        
        if (c.isLogined(email, passwword)){
            cp = new ClientPage(Bank.getClientByEmail(email));
            this.setVisible(false);
            cp.setVisible(true);
        }else if (e.isLogined(email, passwword)){
            EmployeePage ep = new EmployeePage(Bank.getEmployeeByEmail(email));
            this.setVisible(false);
            ep.setVisible(true);
        }else if (a.isLogined(email, passwword)) {
            AdminPage ap = new AdminPage(Bank.getAdminByEmail(email));
            this.setVisible(false);
            ap.setVisible(true);
        }
        else {
            if(email.length() != 0 && passwword.length() != 0) {
                MyDialog d = new MyDialog(false,"you have Entered Invalid data");
            }else{
                if(email.length() == 0) {
                    jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(MyColor.red));
                }
                if (passwword.length() == 0){
                    jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(MyColor.red));
                }
            }
        }
    }//GEN-LAST:event_myButton1ActionPerformed

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton2ActionPerformed

    
    
    public static void loadAdminsData() {
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","hr","hr");
            Statement stmt = con.createStatement();
            String command = "select * from "+Bank.adminsTable;
            ResultSet rs = stmt.executeQuery(command);
            while(rs.next()) {
                String id = rs.getString("id");
                String firstName = rs.getString("FIRST_NAME");
                String lastName = rs.getString("LAST_NAME");
                String email = rs.getString("EMAIL");
                String password = rs.getString("PASSWORD");
                Admin ad = new Admin(id, firstName, lastName, email, password);
                Bank.admins.add(ad);
            }
            con.close();
        }
        catch(Exception e) {
            System.out.println(e);
        }
    }

    public static void loadEmployeesData() {
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","hr","hr");
            Statement stmt = con.createStatement();
            String command = "select * from "+Bank.employeesTable;
            ResultSet rs = stmt.executeQuery(command);
            while(rs.next()) {
                String position = rs.getString("POSITION");
                boolean accepted = Boolean.parseBoolean(rs.getString("ACCEPTED_FLAG"));
                
                String college = rs.getString("COLLEAGE");
                int year = Integer.parseInt(rs.getString("YEAR"));
                String grade = rs.getString("GRADE");
                Qualification qualify = new Qualification(college, year, grade);
                
                String id = rs.getString("id");
                String firstName = rs.getString("FIRST_NAME");
                String lastName = rs.getString("LAST_NAME");
                String email = rs.getString("EMAIL");
                String password = rs.getString("PASSWORD");
                
                Employee emp = new Employee(position, accepted, qualify, id, firstName, lastName, email, password);
                Bank.employees.add(emp);
            }
            con.close();
        }
        catch(Exception e) {
            System.out.println(e);
        }
    }
    
    public static void loadClientsData() {
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","hr","hr");
            Statement stmt = con.createStatement();
            String command = "select * from "+Bank.clientsTable;
            ResultSet rs = stmt.executeQuery(command);
            while(rs.next()) {
                String id = rs.getString("id");
                String firstName = rs.getString("FIRST_NAME");
                String lastName = rs.getString("LAST_NAME");
                String email = rs.getString("EMAIL");
                String password = rs.getString("PASSWORD");
                String phoneNum = rs.getString("PHONE_NUMBER");
                Client cl = new Client(phoneNum, id, firstName, lastName, email, password);
                Bank.clients.add(cl);
            }
            con.close();
        }
        catch(Exception e) {
            System.out.println(e);
        }
    }
    
    public static void loadAccountsData() {
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","hr","hr");
            Statement stmt = con.createStatement();
            String command = "select * from "+Bank.accountsTable;
            ResultSet rs = stmt.executeQuery(command);
            while(rs.next()) {
                String accountNum = rs.getString("ACCOUNT_NUM");
                String accType = rs.getString("TYPE");
                float balance = Float.parseFloat(rs.getString("BALANCE"));
                String status = rs.getString("STATUS");
                String clientId = rs.getString("CLIENT_ID");
                
                String year = rs.getString("YEAR");
                String month = rs.getString("MONTH");
                String day = rs.getString("DAY");
                String dateString = year+"-"+month+"-"+day;
                LocalDate startDate = Bank.getDateFromString(dateString);
                Account ac = new Account(accountNum, accType, balance, status, startDate);
                Bank.getClientById(clientId).accounts.add(ac);
            }
            con.close();
        }
        catch(Exception e) {
            System.out.println(e);
        }
    }
    
    public static void loadTransactoinsData() {
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","hr","hr");
            Statement stmt = con.createStatement();
            String command = "select * from "+Bank.transactionsTable;
            ResultSet rs = stmt.executeQuery(command);
            while(rs.next()) {
                String id = rs.getString("TRANSACTION_ID");
                float amount = Float.parseFloat(rs.getString("AMOUNT"));
                String senderNum = rs.getString("SENDER_NUM");
                String receiverNum = rs.getString("RECEIVER_NUM");

                String year = rs.getString("YEAR");
                String month = rs.getString("MONTH");
                String day = rs.getString("DAY");
                String dateString = year+"-"+month+"-"+day;
                LocalDate date = Bank.getDateFromString(dateString);

                Transaction tr = new Transaction(id, amount, date, senderNum, receiverNum);
                Bank.transactions.add(tr);
                
            }
            con.close();
        }
        catch(Exception e) {
            System.out.println(e);
        }
    }
    
    public static void loadData() {
        loadAdminsData();
        loadEmployeesData();
        loadClientsData();
        loadAccountsData();
        loadTransactoinsData();
    }
    
    public static void main(String args[]) {

        
        loadData();
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private Components.PasswordField jTextField2;
    private myappgui2.MyButton myButton1;
    private myappgui2.MyButton myButton2;
    private Components.MyHeading1 myHeading11;
    // End of variables declaration//GEN-END:variables
}
